[book]
authors = ["Seasawher"]
language = "en"
multilingual = true
src = "src"
title = "Free Resources for Mathematics"

[build]
create-missing = false
build-dir = "book"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/Seasawher/free-math"